### ISSUE TITLE
Pequena correção em um comando errado

### ISSUE THREAD

**Issue by Leofuchs200811** [devaprender/PySimpleGUI-Music-Player#1]
Oi, uma pequena correção, quando você executa ``pip install requirements.txt``, o pip interpreta pra instalar o pacote ``requirements.txt``, mas, como esse pacote não existe, ele mostra um erro

Nesse caso, o comando certo seria ``pip install -r requirements.txt``

**Comment by Jhonatan-de-Souza** [comment]
isso! Não percebi esse erro aqui! 
Valeu!
